<%@ page language="java" contentType="text/html; charset=EUC-KR"
    pageEncoding="EUC-KR"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="EUC-KR">
<title>역명조회</title>
</head>
<body>
<center><h1>역명조회</h1></center>
		<center><h2>경부선 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <a href="honamseon.jsp" target="_self"> 호남선</a> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <a href="jeollaseon.jsp" target="_self">전라선</a></h2></center>
		
 <center><table border="1" width=500 style="text-align:center"></center>
       <tr>
			<td>서울</td>
			<td>남영</td>
			<td>용산</td>
			<td>노량진</td>
			<td>대방</td>
			</tr>
			<tr>
			<td>신길</td>
			<td>영등포</td>
			<td>신도림</td>
			<td>구로</td>
			<td>가산디지털단지</td>
			</tr>
			<tr>
			<td>독산</td>
			<td>금천구청</td>
			<td>석수</td>
			<td>관악</td>
			<td>안양</td>
			</tr>
			<tr>
			<td>명학</td>
			<td>금정</td>
			<td>군포</td>
			<td>당정</td>
			<td>의왕</td>
			</tr>
			<tr>
			<td>성균관대</td>
			<td>화서</td>
			<td>수원</td>
			<td>세류</td>
			<td>병점</td>
			</tr>
			<tr>
			<td>세마</td>
			<td>오산대</td>
			<td>오산</td>
			<td>진위</td>
			<td>송탄</td>
			</tr>
			<tr>
			<td>서정리</td>
			<td>지제</td>
			<td>평택</td>
			<td>성환</td>
			<td>직산</td>
			</tr>
			<tr>
			<td>두정</td>
			<td>천안</td>
			<td>소정리</td>
			<td>전의</td>
			<td>전동</td>
			</tr>
			<tr>
			<td>서창</td>
			<td>조치원</td>
			<td>내판</td>
			<td>부강</td>
			<td>매포</td>
			</tr>
			<tr>
			<td>신탄진</td>
			<td>회덕</td>
			<td>대전조차장</td>
			<td>대전</td>
			<td>세천</td>
			</tr>
			<tr>
			<td>옥천</td>
			<td>이원</td>
			<td>지탄</td>
			<td>심천</td>
			<td>각계</td>
			</tr>
			<tr>
			<td>영동</td>
			<td>황간</td>
			<td>추풍령</td>
			<td>신암</td>
			<td>작지사</td>
			</tr>
			<tr>
			<td>김천</td>
			<td>대신</td>
			<td>아포</td>
			<td>구미</td>
			<td>사곡</td>
			</tr>
			<tr>
			<td>약목</td>
			<td>왜관</td>
			<td>연화</td>
			<td>신동</td>
			<td>지천</td>
			</tr>
			<tr>
			<td>대구</td>
			<td>동대구</td>
			<td>고모</td>
			<td>가천</td>
			<td>경산</td>
			</tr>
			<tr>
			<td>삼성</td>
			<td>남성현</td>
			<td>청도</td>
			<td>신거</td>
			<td>상동</td>
			</tr>
			<tr>
			<td>밀양</td>
			<td>미전</td>
			<td>삼랑진</td>
			<td>원동</td>
			<td>물금</td>
			</tr>
			<tr>
			<td>화명</td>
			<td>구포</td>
			<td>사상</td>
			<td>부산진</td>
			<td>부산</td>
			</tr>
    </table>
</body>
</html>